LearningDiaryLP_ASP/Models/ErrorViewModel.cs
using System;

namespace LearningDiaryLP_ASP.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LearningDiaryLP_ASP/Models/Topic.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LearningDiaryLP_ASP.Models
{
    public partial class Topic
    {

        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int? TimeToMaster { get; set; }
        public int? TimeSpent { get; set; }
        public string Source { get; set; }
        public DateTime? StartLearningDate { get; set; }
        public bool? InProgress { get; set; }
        public DateTime? CompletionDate { get; set; }


        public bool? IsInProgress()
        {
            if (TimeToMaster - TimeSpent <= 0)
            {
                InProgress = false;
            }
            else
            {
                InProgress = true;
            }

            return InProgress;
        }

        public DateTime? EditCompletionDate() //edits completion date to database
        {
            if (TimeToMaster - TimeSpent <= 0)
            {
                CompletionDate = Convert.ToDateTime(StartLearningDate).AddDays(Convert.ToDouble(TimeSpent));
            }
            else if (TimeToMaster - TimeSpent > 0)
            {
                CompletionDate = Convert.ToDateTime(StartLearningDate).AddDays(Convert.ToDouble(TimeToMaster));
            }

            return CompletionDate;

        }
    }
}

LearningDiaryLP_ASP/Controllers/HomeController.cs
using LearningDiaryLP_ASP.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LearningDiaryLP_ASP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LearningDiaryLP_ASP/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LearningDiaryLP_ASP.Data;
using LearningDiaryLP_ASP.Models;

namespace LearningDiaryLP_ASP.Controllers
{
    public class TopicsController : Controller
    {
        private readonly LearningDiaryLP_ASPContext _context;

        public TopicsController(LearningDiaryLP_ASPContext context)
        {
            _context = context;
        }

        // GET: Topics
        public async Task<IActionResult> Index()
        {
            return View(await _context.Topic.ToListAsync());
        }

        // GET: Topics/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topic = await _context.Topic
                .FirstOrDefaultAsync(m => m.Id == id);
            if (topic == null)
            {
                return NotFound();
            }

            return View(topic);
        }

        // GET: Topics/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Topics/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,TimeToMaster,TimeSpent,Source,StartLearningDate,CompletionDate")] Topic topic)
        {
            
            if (ModelState.IsValid)
            {
                topic.IsInProgress();
                topic.EditCompletionDate();
                _context.Add(topic);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(topic);

        }

        // GET: Topics/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topic = await _context.Topic.FindAsync(id);
            if (topic == null)
            {
                return NotFound();
            }
            return View(topic);
        }

        // POST: Topics/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,TimeToMaster,TimeSpent,Source,StartLearningDate,InProgress,CompletionDate")] Topic topic)
        {
            if (id != topic.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    topic.IsInProgress();
                    topic.EditCompletionDate();
                    _context.Update(topic);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TopicExists(topic.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(topic);
        }

        // GET: Topics/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topic = await _context.Topic
                .FirstOrDefaultAsync(m => m.Id == id);
            if (topic == null)
            {
                return NotFound();
            }

            _context.Topic.Remove(topic);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }

        // POST: Topics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var topic = await _context.Topic.FindAsync(id);
            _context.Topic.Remove(topic);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TopicExists(int id)
        {
            return _context.Topic.Any(e => e.Id == id);
        }
    }
   
}

LearningDiaryLP_ASP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<link href="~/css/home.css" rel="stylesheet" />
<div class="container" id="homepage">
    <div class="text-center" id="homeScreen">
        <h1 class="display-4">LEARNING DIARY</h1>
        <h4>by Lasse Parviainen</h4>
    </div>
</div>

LearningDiaryLP_ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LearningDiaryLP_ASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
            <div class="wrapper">
                <nav class="sidenav">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <h4>Learning Diary</h4>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Topics" asp-action="Index">Check entry list</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Topics" asp-action="Create">Add entry</a>
                        </li>
                        <li class="nav-item">
                            <div class="container nav-item">
                                <button type="submit" class="btn" onclick="openPopup()">Instructions</button>
                                
                            </div>
                        </li>
                        <li>
                            <div class="container">
                                <footer class="border-top footer text-muted container-flui">
                                    <div class="container">
                                        &copy; 2022 - Learning Diary by Lasse Parviainen
                                    </div>
                                </footer>
                            </div>
                        </li>
                    </ul>
                </nav>
            </div>
                <div class="container-fluid" id="page">
                    <main role="main" class="pb-3">
                        @RenderBody()
                        <div class="popup" id="popup">
                            <p>Mene töihin</p>
                            <button type="button" onclick="closePopup()">ok</button>
                        </div>
                    </main>
                </div>
        
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
<script src="~/js/site.js"></script>
</body>
</html>

LearningDiaryLP_ASP/Views/Topics/Create.cshtml
@model LearningDiaryLP_ASP.Models.Topic

@{
    ViewData["Title"] = "Create";
}

<link href="~/css/create.css" rel="stylesheet" />
<h1>Add entry</h1>

<div class="row">

    <div class="container" id="createIndex">
        <div class="container-fluid">
            <div class="col">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" id="inputfield" onmouseover="grey(this)" onmouseout="white(this)" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" id="inputfield" onmouseover="grey(this)"onmouseout="white(this)" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TimeToMaster" class="control-label"></label>
                        <input asp-for="TimeToMaster" class="form-control" id="inputfield" onmouseover="grey(this)"onmouseout="white(this)"/>
                        <span asp-validation-for="TimeToMaster" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TimeSpent" class="control-label"></label>
                        <input asp-for="TimeSpent" class="form-control" id="inputfield" onmouseover="grey(this)"onmouseout="white(this)" />
                        <span asp-validation-for="TimeSpent" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Source" class="control-label"></label>
                        <input asp-for="Source" class="form-control" id="inputfield" onmouseover="grey(this)"onmouseout="white(this)"/>
                        <span asp-validation-for="Source" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="StartLearningDate" class="control-label"></label>
                        <input asp-for="StartLearningDate" type="date" class="form-control"  onmouseover="grey(this)"onmouseout="white(this)"/>
                        <span asp-validation-for="StartLearningDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Add entry" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col">
        <div class="btn btn-primary" id="back">
            <a asp-action="Index">Back to List</a>
        </div>
    </div>
</div>
<script src="~/js/site.js"></script>

LearningDiaryLP_ASP/Views/Topics/Delete.cshtml
@model LearningDiaryLP_ASP.Models.Topic

@{
    ViewData["Title"] = "Delete";
}
<link href="~/css/detailsEdit.css" rel="stylesheet" />
<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Topic</h4>
    <hr />
    <div class="container" id="info">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.TimeToMaster)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TimeToMaster)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.TimeSpent)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TimeSpent)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Source)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Source)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.StartLearningDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.StartLearningDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.InProgress)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.InProgress)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CompletionDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CompletionDate)
            </dd>
        </dl>
    </div>

    <form asp-action="Delete" id="deletion">
        <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this entry?')" />
        <input type="hidden" asp-for="Id" />
        <a asp-action="Index">Back to List</a>
    </form>

</div>

LearningDiaryLP_ASP/Views/Topics/Details.cshtml
@model LearningDiaryLP_ASP.Models.Topic

@{
    ViewData["Title"] = "Details";
}
<link href="~/css/detailsEdit.css" rel="stylesheet" />
<h1>Details</h1>

<div>
    <div class="container" id="title">
        <h4>@Html.DisplayFor(model => model.Id). @Html.DisplayFor(model => model.Title)</h4>
    </div>

    <div class="container" id="info">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.TimeToMaster)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TimeToMaster)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.TimeSpent)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TimeSpent)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Source)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Source)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.StartLearningDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.StartLearningDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.InProgress)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.InProgress)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CompletionDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CompletionDate)
            </dd>
        </dl>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

LearningDiaryLP_ASP/Views/Topics/Edit.cshtml
@model LearningDiaryLP_ASP.Models.Topic

@{
    ViewData["Title"] = "Edit";
}

<link href="~/css/detailsEdit.css" rel="stylesheet" />
<h1>Edit</h1>


<div class="container-fluid" id="info">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TimeToMaster" class="control-label"></label>
                    <input asp-for="TimeToMaster" class="form-control" />
                    <span asp-validation-for="TimeToMaster" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TimeSpent" class="control-label"></label>
                    <input asp-for="TimeSpent" class="form-control" />
                    <span asp-validation-for="TimeSpent" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Source" class="control-label"></label>
                    <input asp-for="Source" class="form-control" />
                    <span asp-validation-for="Source" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="StartLearningDate" class="control-label"></label>
                    <input asp-for="StartLearningDate" type="date" class="form-control" />
                    <span asp-validation-for="StartLearningDate" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

LearningDiaryLP_ASP/Views/Topics/Index.cshtml
@model IEnumerable<LearningDiaryLP_ASP.Models.Topic>


@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="text-center">
        <h1 class="display-4">LEARNING DIARY</h1>
        
    </div>
</div>

<div class="row" id="entrylist">
    <div class="col">
        <div class="table-responsive">
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Title)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Description)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TimeToMaster)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TimeSpent)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Source)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.StartLearningDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.InProgress)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CompletionDate)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>


                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TimeToMaster)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TimeSpent)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Source)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StartLearningDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.InProgress)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CompletionDate)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this entry?')">Delete</a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>